# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - group10bestteam

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_f98550736b724374ab31c1b3ae39415e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2f99cda8c1204ff88c8a4faa8c0bfbc6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f98550736b724374ab31c1b3ae39415e }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'group10bestteam'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1ceb1bec81d94cbcac204941bda3facc }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f98550736b724374ab31c1b3ae39415e }}/appsvc/staticsite:${{ github.sha }}'